### ISSUE TITLE
Contact Form not working

### ISSUE THREAD

**Issue by striebwj** [ClassicPress/ClassicPress-Network#56]
The contact form on the new website returns and error:

```
message: "There was an error trying to send your message. Please try again later."
status: "mail_failed"
```

**Comment by timbocode** [comment]
I think this is happening because the email domain (gmail.com) in the "To:" field is different to the web domain (somethingelse.com). It just needs real entries adding to the contact form. It will still need testing before going live of course.

**Comment by nylen** [comment]
In addition to the above, I had to configure an SMTP server. I used https://wordpress.org/plugins/wp-smtp/ for this.

With that done, this issue is fixed.

**Comment by striebwj** [comment]
Are using Amazon SES here? I still have the details @scottybo sent me to use for the forums.
